# Generated by Django 4.1.7 on 2023-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('frase', models.CharField(max_length=140)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Persona',
            new_name='Moderador',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RenameField(
            model_name='moderador',
            old_name='fecha_nacimiento',
            new_name='fecha_registro',
        ),
    ]
